name: Code Coverage Report
description: Comments a pull request with the code coverage
author: Romeo Van Snick
branding:
  icon: check-square
  color: green
inputs:
  github-token:
    description: Github token
    required: true
  lcov-file:
    description: The location of the lcov.info file
    required: false
  lcov-base:
    description: The location of the lcov file for the base branch
    required: false
  show-uncovered-lines:
    description: Set to true to show the uncovered lines column
    required: false
  show-color-emoji:
    description: Set to true to show a colored emoji if the coverage decreased or increased
    required: false
  show-old-value-for-files:
    description: Set to true to show the old coverage result value
    required: false
    default: 'true'
  show-increase-per-files:
    description: Set to true to show the increase/decrease difference of the coverage;
    required: false

runs:
  using: node12
  main: dist/main.js
